app = "slack-corefone-payroll-bot"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 1000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
